### PR TITLE
Do not trim the values after macros/placeholders are applied

### PR DESCRIPTION
**Pull request by geoffwhittington**

### CODE REVIEW

**Comment by hhaidar** [comment]
cc @hhaidar

**Comment by sibartlett** [comment]
Why do we not want to trim them?

**Comment by geoffwhittington** [comment]
I'll throw it back, why do we want to trim?

**Comment by geoffwhittington** [comment]
We have a production issue where someone has a value that has a trailing space

**Comment by sibartlett** [comment]
lol amazing, well I suppose I bless this pull request +1

**Comment by hhaidar** [comment]
dying lmao

**Pull request merged**
