### PR TITLE
HP ALM: Request a QCSession cookie after authenticating

### PR DESCRIPTION
**Pull request by sibartlett**

### CODE REVIEW

**Comment by geoffwhittington** [comment]
@sibartlett Did you push all of your local commits?

**Comment by sibartlett** [comment]
I have a second branch pushed called hp_test.

**Comment by funkaoshi** [comment]
We going to merge this?

**Comment by geoffwhittington** [comment]
No, we shouldn't. I'll remove the PR but keep the branch.

**Pull request closed without merging**
