### PR TITLE
Fix Atlassian bug JSW-10340

### PR DESCRIPTION
**Pull request by geoffwhittington**

### CODE REVIEW

**Comment by geoffwhittington** [comment]
@sibartlett can you review and merge if you like it? I've tested that I can successfully populate a string and Epic Link field

**Comment by geoffwhittington** [comment]
Seems I have a linting error.... whats the best way of doing this continuation?

**Comment by sibartlett** [comment]
Nice, you beat me to it!

**Comment by sibartlett** [comment]
I force pushed a lint fix.

**Pull request merged**
