### PR TITLE
Scanner Mapping Update

### PR DESCRIPTION
**Pull request by afshar-g**
Updated ASoC-DAST, AppScan, Checkmarx, ThreadFix, WebInspect and WhiteHat code scanner mappings.

### CODE REVIEW

**Comment by geoffwhittington** [comment]
This is an epic pull request. I think this is a new record! I don't think @sibartlett nor I can really review this sort of change. Best we can do is validate that the CSV files look valid.

**Comment by sibartlett** [comment]
What version of SDE do we want this in?

**Comment by geoffwhittington** [comment]
Thats a Mark R. question. We'll have to drop "Beta" from Checkmarx, and Threadfix in the app once we merge into SDE.

**Comment by afshar-g** [comment]
Yeah, we just need a high-level validation of the files and the format from you for review. The content team has already reviewed the mappings themselves.

**Comment by afshar-g** [comment]
Please let me know which version of SDE this goes into when you decide, so I can update the release notes accordingly.

**Comment by sibartlett** [comment]
Mark has given the OK to put this in 4.8, unless wither of you object?

**Comment by afshar-g** [comment]
Perfect. Sounds good to me. Thanks.

**Comment by shawngustaw** [comment]
Very epic PR. Awesome stuff @afshar-g !

**Pull request merged**
