### PR TITLE
Fix unicode issues with ldap group names

### PR DESCRIPTION
**Pull request by RouganStriker**
Refs #SDE-3738

### CODE REVIEW

**Comment by harry-kim** [comment]
can we test this?

**Comment by emintham** [comment]
+1

**Comment by JeffBain** [comment]
Code change looks fine. Harry makes a good point about testing if possible, though I assume maybe this is tricky to test since the place we run into issues is during the sync, correct?

**Comment by RouganStriker** [comment]
Yea, we can manually test it using LDAP groups with unicode characters in the anme

**Pull request merged**
